import { Footer } from '@/components/footer/footer'
import { Navbar } from '@/components/nav-bar/nav-bar'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className="h-full">
      <body className={cn('relative h-full antialiased', inter.className)}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <main className="relative flex min-h-screen flex-col">
          <Navbar />
          <div className="flex-1 flex-grow">{children}</div>
          <Footer />
        </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
